### ISSUE TITLE
Initial attempt

### ISSUE THREAD

**Issue by fre4kyC0de** [fail0verflow/hbc#1] opened 2016-11-30 21:27 UTC
The open HBC opens fine and displays like its "official" brother. Runnning on a PAL Wii. System Menu 4.3E. IOS80 & IOS36 are Trucha-patched, iOS236 (==IOS36) and multiple revisions of d2x-cIOS (some 2xx-slots) are installed. No BootMii as running on newer hardware. Compiled under Ubuntu 16.10 amd64 inside VBox (fresh setup & fully updated as I'm writing this).

WORKING:
- lists homebrew applications from SD
- switch of styles
- settings menu

BROKEN:
- does not save the last style
- does not load any homebrew
- fails to return to the Wii Menu (maybe related to the previos point) [just displays black screen]
- WiFi icon blinking all the time

UNTESTED:
- ShutDown
- USB-access

**Comment by marcan** [comment] 2016-12-01 06:34
Needs more info. What version of devkitPPC, libogc, external libs were used to build this? What commit exactly did you build off of? Did you make any changes? What IOS is it running on? There is no support whatsoever for patched IOSes, so if the IOS you're running under is not vanilla, or you're using any other kind of starlet-side modification, please close.

Try [this binary](https://mrcn.st/t/channel_retail.wad). If that works, the problem is with your build environment.

Loading homebrew works fine in Dolphin (after bugfixes to the emulator) so I'd be surprised if it doesn't work on real hardware.

**Comment by fre4kyC0de** [comment] 2016-12-01 21:47
**Wii:**
HBC is running on vanilla IOS58. No changes to the default IOSes (except for Trucha patched into IOS80). Just added d2x-IOSes to the 2xx-slots.
HBC 1.1.2 works fine

**Build environment:**
Ubuntu 16.10 amd64 running inside VirtualBox 5.1.10. Fresh installation and fully updated. Then installed Python, "build-essential" and the packages listed in the README here.
Installed devkitPPC using the script from https://sourceforge.net/projects/devkitpro/files/Automated%20Installer/
Installed to /opt/devkitPro. Then added the paths (adjusted to my path) like here: http://devkitpro.org/wiki/Getting_Started/devkitPPC
libogcfat: 1.0.14
gamecube-examples 20161115
devkitPPC 28
wiiexamples 20161115
libogc 1.8.15

Portlibs from here: https://sourceforge.net/projects/devkitpro/files/portlibs/ppc/
expat 2.0.1
freetype 2.4.2
jpeg 8d
libpng 1.5.4
mxml 2.6
tremor-lowmem
zlib 1.2.5

**Comment by fre4kyC0de** [comment] 2016-12-01 21:51
Your WAD fails too. Same issue.
The one provided here (https://wiidatabase.de/downloads/kanaele/homebrewkanal-open-source-edition/) instead works fine.

**Comment by marcan** [comment] 2016-12-01 22:14
Sigh, if theirs works and mine doesn't I bet the devkitPPC/libogc update broke something and they used an older build. Weird that it works in Dolphin though. I guess ill have to debug it on real hardware...
-- 
Hector Martin "marcan" (marcan@marcan.st)
Public key: https://mrcn.st/pub

**Comment by fre4kyC0de** [comment] 2016-12-02 04:49
Big thanks.
If I can help, please tell me.

**Comment by fre4kyC0de** [comment] 2016-12-02 22:27
Just tested a self-compiled [859b04b]. It has the same issue. So it's definitely caused by the build environment.

**Comment by Brawl345** [comment] 2016-12-08 20:01
Hello, I'm the administrator of the WiiDatabase and compiled the version linked above. I compiled it on Windows 10 in the Windows on Linux Subsystem (no comments about this please!) which equals to Ubuntu 14.04. I installed devkitPro, devkitPPC and the portlibs on the same day the HBC was open-sourced, so the versions should be the same as fre4kyC0de's. My devkitPro folder is in $HOME. My Python verison is 2.7.6.

**Comment by fre4kyC0de** [comment] 2016-12-08 21:14
Which version of Windows 10 did you use?
Build 14393? amd64 or x86?
I used Ubuntu inside VirtualBox running on an Windows 7 amd64 host.
Will now try to use Ubuntu 14.04.5 amd64 as build environment.

**Comment by Brawl345** [comment] 2016-12-08 21:14
Yup, 14393.447, amd64.

**Comment by fre4kyC0de** [comment] 2016-12-10 11:31
Just tested with an Ubuntu 14.04.5 amd64 VM. Fully updated and same build environment as described before. Still fails.

@Brawl345 
Could you build against the newest source code and upload the complete build-folder? The one you cloned from github? Then we could compare, which files differ from mine

**Comment by Brawl345** [comment] 2016-12-10 20:47
@fre4kyC0de You mean clone + compile? Here it is: https://dl.dropboxusercontent.com/u/32829149/hbc%20build.tar.gz2

**Comment by fre4kyC0de** [comment] 2016-12-12 20:16
@Brawl345 
The greatest difference between my. build and yours is, that my Ubuntu-version used gcc 6.2.0 to compile and yours used gcc 4.6.3. Also you used devkitPPC rev 26 while I used rev 28.

@marcan 
Maybe some incompatibility with the new gcc or devkitPPC?

**Comment by Brawl345** [comment] 2016-12-18 12:01
Looks like devkitPPC is broken, Same is happening in the Wii U scene: https://gbatemp.net/threads/building-home-brew-launcher.453403/#post-6930214

**Comment by marcan** [comment] 2016-12-18 12:38
Yeah that stupid s32 change caused many warnings in HBC for all the printfs (which I fixed before release). I guess I shouldn't be surprised it broke more things.

**Comment by fre4kyC0de** [comment] 2016-12-18 21:21
But r26 should work?
Do I need to downgrade devkitPro, too?

**Comment by fre4kyC0de** [comment] 2016-12-20 21:14
Just tested with devkitPPC r26 & libogc 1.8.11.1 & libfat-ogc 1.0.11.
Works. Will retry with most recent libogc and report here.

**Comment by mariogamer2** [comment] 2017-01-01 19:17
So the build work with what exactly please?

**Comment by fre4kyC0de** [comment] 2017-01-04 21:12
**Wii:**
HBC is running on vanilla IOS58. No changes to the default IOSes (except for Trucha patched into IOS80). Just added d2x-IOSes to the 2xx-slots.
HBC 1.1.2 works fine

**Build environment:**
Ubuntu 14.04.5 amd64 running inside VirtualBox 5.1.10. Fresh installation and fully updated. Then installed Python, "build-essential" and the packages listed in the README here.
Installed devkitPPC using the script from https://sourceforge.net/projects/devkitpro/files/Automated%20Installer/
Installed to /opt/devkitPro. Then added the paths (adjusted to my path) like here: http://devkitpro.org/wiki/Getting_Started/devkitPPC
libogcfat: 1.0.14
gamecube-examples 20161115
devkitPPC 28
wiiexamples 20161115
libogc 1.8.15

Portlibs from here: https://sourceforge.net/projects/devkitpro/files/portlibs/ppc/
expat 2.0.1
freetype 2.4.2
jpeg 8d
libpng 1.5.4
mxml 2.6
tremor-lowmem
zlib 1.2.5

This one fails.

---------------------------------------------------------------------------------

Replacing devkitPPC with r26; libogc with version 1.8.11.1 and libfat-ogc with version 1.0.12 works.

---------------------------------------------------------------------------------

Updating libogc & libfat-ogc to the most recent version again breaks the build.

**Comment by DjDiabolik** [comment] 2017-11-18 02:11
@Brawl345  Very interesting........... i want to try to OHBC at today (Letztes Update: 14.10.2017 Version: v1.1.4-1 (FIX94-Fork) ) but if obtain problems how i can reinstall the "original" 1.1.2 ?
I can use WAM to install this wad ?

**Comment by Brawl345** [comment] 2017-11-18 17:58
@DjDiabolik The original won't be overwritten, because the OHBC has another Title ID. You can use any up-to-date WAD manager to install the WAD (YAWMM f.e.)

**Comment by Madridi7** [comment] 2018-03-19 01:01
So can someone clarify? Does that mean that up to the latest commit, HBC has a few big bugs?
I mean, listed in OP as broken is "does not load any homebrew", which is pretty big in my opinion.

I am a bit confused. Are we talking about building issues here (seeing as that where the conversation shifted to), or is there actual bugs here?

**Comment by Brawl345** [comment] 2018-03-19 01:03
Just building issues with the latest devkitPPC, works fine otherwise (the other issues were fixed with a fixed TMD in 859b04bc37182a69e3b6322b47a850e5e4e0a4ef I believe).

**Comment by Madridi7** [comment] 2018-03-19 01:07
Perfect thanks. In that case, shouldn't this issue be closed?

**Comment by dhewg** [comment] 2019-02-04 07:04
yup, sounds like this can be closed

**Closed by dhewg** 2019-02-04 07:04 UTC
